apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: gitops-argocd
  newName: /gitops-argocd
  newTag: e87f9822aa322a07713a577ee26e4172d090a62c
resources:
- ../../base
